-- MySQL Script generated by MySQL Workbench
-- Fri Oct  6 10:20:18 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pvpv_final
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pvpv_final
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pvpv_final` DEFAULT CHARACTER SET utf8 ;
USE `pvpv_final` ;

-- -----------------------------------------------------
-- Table `pvpv_final`.`TipoDocumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pvpv_final`.`TipoDocumento` (
  `idTipoDocumento` VARCHAR(5) NOT NULL,
  `TipoDocumento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoDocumento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pvpv_final`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pvpv_final`.`Rol` (
  `idRol` INT NOT NULL,
  `EstadoRol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pvpv_final`.`Ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pvpv_final`.`Ciudad` (
  `idCiudad` INT NOT NULL,
  `NombreCiudad` VARCHAR(45) NULL,
  PRIMARY KEY (`idCiudad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pvpv_final`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE Usuario (
  `PKNUsuario` INT NOT NULL,
  `PrimerNombreUsu` VARCHAR(45) NOT NULL,
  `SegundoNombreUsu` VARCHAR(45) NULL,
  `PrimerApellidoUsu` VARCHAR(45) NOT NULL,
  `SegundoApellidoUsu` VARCHAR(45) NULL,
  `DireccionUsu` VARCHAR(45) NOT NULL,
  `TelefonoUsu` INT NULL,
  `CelularUsu` BIGINT(15) NULL,
  `EmailUsu` VARCHAR(45) NOT NULL,
  `FechaNacimientoUsu` VARCHAR(45) NOT NULL,
  `PassUsu` VARCHAR(45) NOT NULL,
  `TipoDocumento_idTipoDocumento` VARCHAR(5) NOT NULL,
  `Rol_idRol` INT NOT NULL,
  `Ciudad_idCiudad` INT NOT NULL,
  PRIMARY KEY (`PKNUsuario`, `TipoDocumento_idTipoDocumento`),
  INDEX `fk_Usuario_TipoDocumento_idx` (`TipoDocumento_idTipoDocumento` ASC),
  INDEX `fk_Usuario_Rol1_idx` (`Rol_idRol` ASC),
  INDEX `fk_Usuario_Ciudad1_idx` (`Ciudad_idCiudad` ASC),
  CONSTRAINT `fk_Usuario_TipoDocumento`
    FOREIGN KEY (`TipoDocumento_idTipoDocumento`)
    REFERENCES `pvpv_final`.`TipoDocumento` (`idTipoDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Rol1`
    FOREIGN KEY (`Rol_idRol`)
    REFERENCES `pvpv_final`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Ciudad1`
    FOREIGN KEY (`Ciudad_idCiudad`)
    REFERENCES `pvpv_final`.`Ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pvpv_final`.`Conteo_Visitas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pvpv_final`.`Conteo_Visitas` (
  `IdConteoVisitas` INT NOT NULL AUTO_INCREMENT,
  `Visitas` INT NOT NULL,
  `Usuario_PKNUsuario` INT NOT NULL,
  `Usuario_TipoDocumento_idTipoDocumento` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`IdConteoVisitas`),
  INDEX `fk_Conteo_Visitas_Usuario1_idx` (`Usuario_PKNUsuario` ASC, `Usuario_TipoDocumento_idTipoDocumento` ASC),
  CONSTRAINT `fk_Conteo_Visitas_Usuario1`
    FOREIGN KEY (`Usuario_PKNUsuario` , `Usuario_TipoDocumento_idTipoDocumento`)
    REFERENCES `pvpv_final`.`Usuario` (`PKNUsuario` , `TipoDocumento_idTipoDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pvpv_final`.`TamañoPresentacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pvpv_final`.`TamañoPresentacion` (
  `IdTamañoPresentacion` INT NOT NULL,
  `DescripcionTP` VARCHAR(45) NULL,
  PRIMARY KEY (`IdTamañoPresentacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pvpv_final`.`TipoProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pvpv_final`.`TipoProducto` (
  `IdTipoProducto` INT NOT NULL,
  `DescripcionTipoProducto` VARCHAR(45) NULL,
  PRIMARY KEY (`IdTipoProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pvpv_final`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pvpv_final`.`Producto` (
  `IDProducto` INT NOT NULL,
  `DescripcionPro` VARCHAR(45) NOT NULL,
  `PrecioUnitarioPro` DECIMAL(19,5) NOT NULL,
  `ObservPro` VARCHAR(45) NOT NULL,
  `Productocol` VARCHAR(45) NOT NULL,
  `TamañoPresentacion_IdTamañoPresentacion` INT NOT NULL,
  `TipoProducto_IdTipoProducto` INT NOT NULL,
  PRIMARY KEY (`IDProducto`),
  INDEX `fk_Producto_TamañoPresentacion1_idx` (`TamañoPresentacion_IdTamañoPresentacion` ASC),
  INDEX `fk_Producto_TipoProducto1_idx` (`TipoProducto_IdTipoProducto` ASC),
  CONSTRAINT `fk_Producto_TamañoPresentacion1`
    FOREIGN KEY (`TamañoPresentacion_IdTamañoPresentacion`)
    REFERENCES `pvpv_final`.`TamañoPresentacion` (`IdTamañoPresentacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_TipoProducto1`
    FOREIGN KEY (`TipoProducto_IdTipoProducto`)
    REFERENCES `pvpv_final`.`TipoProducto` (`IdTipoProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pvpv_final`.`Recibio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pvpv_final`.`Recibo` (
  `idRecibo` INT NOT NULL,
  `FechaRecibo` DATE NOT NULL,
  `TotalRecibo` DECIMAL(19,5) NOT NULL,
  `Usuario_PKNUsuario` INT NOT NULL,
  `Usuario_TipoDocumento_idTipoDocumento` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`idRecibo`),
  INDEX `fk_Recibio_Usuario1_idx` (`Usuario_PKNUsuario` ASC, `Usuario_TipoDocumento_idTipoDocumento` ASC),
  CONSTRAINT `fk_Recibio_Usuario1`
    FOREIGN KEY (`Usuario_PKNUsuario` , `Usuario_TipoDocumento_idTipoDocumento`)
    REFERENCES `pvpv_final`.`Usuario` (`PKNUsuario` , `TipoDocumento_idTipoDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pvpv_final`.`Recibio_has_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pvpv_final`.`Recibio_has_Producto` (
  `Recibio_idRecibio` INT NOT NULL,
  `Producto_IDProducto` INT NOT NULL,
  `CantidadProducto` INT NOT NULL,
  `ValorVenta` DECIMAL(19,5) NOT NULL,
  PRIMARY KEY (`Recibio_idRecibio`, `Producto_IDProducto`),
  INDEX `fk_Recibio_has_Producto_Producto1_idx` (`Producto_IDProducto` ASC),
  INDEX `fk_Recibio_has_Producto_Recibio1_idx` (`Recibio_idRecibio` ASC),
  CONSTRAINT `fk_Recibio_has_Producto_Recibio1`
    FOREIGN KEY (`Recibio_idRecibio`)
    REFERENCES `pvpv_final`.`Recibio` (`idRecibo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recibio_has_Producto_Producto1`
    FOREIGN KEY (`Producto_IDProducto`)
    REFERENCES `pvpv_final`.`Producto` (`IDProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
